####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                _  _       _  __ _ _     _   _   _                                              | #
# |               | |/ /_ __ (_)/ _` | |__ | |_| |_| | ___  _ __  __  ___  ___                    | #
# |               | ' /| '_ \| | (_| | '_ \|  _|  _  |/ _ \| '_ \'_ \/ __|/ _ \                    | #
# |               | . \| | | | |\__, | | | \ |_| | | | (_) | | | | | \__ \  __/                    | #
# |               |_|\_\_| |_|_|\___/|_| |_|\__|_| |_|\___/|_| |_| |_|___/\___|                    | #
# |                                                                                              | #
# |                              KNIGHT HOMES - CONFIGURATION                                     | #
# |                                                                                               | #
# |         DISCORD:     https://discord.gg/uySRT32aRD                                           | #
# |                                                                                               | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################


# +----------------------------------------------------------------------------------------------+ #
# |                                           ICONS                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define Unicode icons for different actions. These are shown in messages.    
icons:
  player: "⭐"                      # Shown before player names
  homes_owned: "🏠"                 # Shown before personal home names/messages
  home_slot: "▣"                    # Used for home slots   
  empty_slot: "🫙"                  # Used for empty slots
  locked_slot: "🔒"                 # Used for locked slots
  delete_home: "❌"                 # Used for home deletion
  set_home: "➕"                    # Used when setting a home  
  set_home_confirmed: "✔"           # Used when home is set successfully
  teleport_cancelled: "✖"           # Used when teleportation is cancelled
  teleporting: "✈"                  # Used when teleporting
  combat_teleport_blocked: "⛔"     # Shown when teleport is blocked due to combat
  home_teleport_success: "🌀"       # Shown when teleported successfully
  home_deleted: "🗑"                 # Shown when home is deleted
  out_of_combat: "🛡"                # Shown when player out of combat
  in_combat: "⚔"                    # Shown when player enters combat
  teleport_cooldown: "⛔"           # Used for teleport cooldown

# +----------------------------------------------------------------------------------------------+ #
# |                                           COLORS                                             | #
# +----------------------------------------------------------------------------------------------+ #

# Colors use '&' codes and are applied to icons/messages.
colors:
  player: "&6"                       # Gold
  homes_owned: "&f"                  # White
  home_slot: "&a"                    # Green
  empty_slot: "&7"                   # Gray
  locked_slot: "&4"                  # Dark Red
  delete_home: "&4"                  # Dark Red
  set_home: "&e"                     # Yellow
  set_home_confirmed: "&e"           # Yellow
  teleport_cancelled: "&4"           # Dark Red
  teleporting: "&f"                  # White
  combat_teleport_blocked: "&4"      # Dark Red
  home_teleport_success: "&2"        # Dark Green
  home_deleted: "&4"                 # Dark Red
  out_of_combat: "&2"                # Dark Green
  in_combat: "&4"                    # Dark Red
  teleport_cooldown: "&4"            # Dark Red

# +----------------------------------------------------------------------------------------------+ #
# |                                         MISC                                                 | #
# +----------------------------------------------------------------------------------------------+ #

cooldown:
  enabled: true
  time: 1 # minutes
  bypass-permission: knighthomes.cooldown.bypass

combat-teleport-block: true
